FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-run

WORKDIR /usr/src
COPY . .

RUN yarn
RUN yarn build
RUN curl https://www.kozco.com/tech/LRMonoPhase4.wav --silent --output test.wav

# Run: "node play.js" or "node echo.js"
CMD [ "balena-idle" ]